### ISSUE TITLE
information_mutual throws TypeError:

### ISSUE THREAD

**Issue by bon** [pafoster/pyitlib#1]
After install via pip under python2.7 then following the examples in the docs until

    drv.information_mutual(X)

This throws the error

    TypeError: 'numpy.float64' object cannot be interpreted as an index

**Comment by pafoster** [comment]
Thanks for reporting this. I believe this relates to NumPy 1.12 and later versions, which removed deprecated support for floating point indices.

I've released a new version with some fixes. Please could you confirm whether this error still appears?

**Comment by bon** [comment]
Yes, working in 77b1fe01. Thanks!
