### ISSUE TITLE
API documentation missing on https://pafoster.github.io/pyitlib/

### ISSUE THREAD

**Issue by BraveDistribution** [pafoster/pyitlib#6]
docstrings are fine in the code, but the formatted docstrings are missing on the page mentioned above.

![image](https://user-images.githubusercontent.com/36101458/68275565-57ef7400-006c-11ea-8dcb-0cfb552242a9.png)

**Comment by pafoster** [comment]
Thanks for raising this. I've regenerated the html docs.
